name: codacy-coverage-reporter

on:
  push:
    branches: [ 5.0.x ]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@master
      - name: Init PHP Environment
        run: |
          sudo apt-get update
          sudo apt-get install curl zip openssl
          sudo apt-get install php-cli php-common php-redis php-curl php-zip php-mbstring php-xdebug php-gd php-gmp php-json php-tokenizer php-xml php-sqlite3 php-igbinary
          sudo apt-get install composer
          php -r "phpinfo();"
      - name: Download Code Climate Reporter
        run: |
          wget https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          chmod +x test-reporter-latest-linux-amd64
      - name: Update dependencies
        run: |
          composer self-update
          composer update
        env:
          COMPOSER_MEMORY_LIMIT: -1
      - name: Prepare Reporter
        run: ./test-reporter-latest-linux-amd64 before-build
      - name: Run Unit Tests
        run: ./vendor/bin/phpunit
      - name: Send report to Code Climate
        run: ./test-reporter-latest-linux-amd64 after-build -t clover -r ${{ secrets.CC_REPORTER_ID }}
      - name: Run codacy-coverage-reporter
        uses: mrfyda/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
